// Student data for Programme FUTUR
const students = [
    {
        id: 1,
        matricule: 'PF-NATI-2025-1002',
        name: 'NTOUA C. Crepin',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/1.jpg',
    },
    {
        id: 2,
        matricule: 'PF-NATI-2025-1003',
        name: 'HAMIDOU S. Fleury',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/2.jpg',
    },
    {
        id: 3,
        matricule: 'PF-NATI-2025-1004',
        name: 'MOUHAMADOU H. Hadjalatou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/3.jpg',
    },
    {
        id: 4,
        matricule: 'PF-NATI-2025-1005',
        name: 'LAFIA S. Samadou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/4.jpg',
    },
    {
        id: 5,
        matricule: 'PF-NATI-2025-1007',
        name: 'SITOU D. Waidi',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/5.jpg',
    },
    {
        id: 6,
        matricule: 'PF-NATI-2025-1008',
        name: 'KPOIKPO M. Real',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/6.jpg',
    },
    {
        id: 7,
        matricule: 'PF-NATI-2025-1009',
        name: 'ILOUKOURA A. Olivier',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/7.jpg',
    },
    {
        id: 8,
        matricule: 'PF-NATI-2025-1010',
        name: 'SANNI Gania',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/8.jpg',
    },
    {
        id: 9,
        matricule: 'PF-NATI-2025-1011',
        name: 'DOSSOU Nelson',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/9.jpg',
    },
    {
        id: 10,
        matricule: 'PF-NATI-2025-1012',
        name: 'ALASSANE Nazifath',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/10.jpg',
    },
    {
        id: 11,
        matricule: 'PF-NATI-2025-1013',
        name: 'ALAZA C. Yarou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/11.jpg',
    },
    {
        id: 12,
        matricule: 'PF-NATI-2025-1014',
        name: 'TCHAMPENA Ashley',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/12.jpg',
    },
    {
        id: 13,
        matricule: 'PF-NATI-2025-1015',
        name: 'BABA Miradj',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/13.jpg',
    },
    {
        id: 14,
        matricule: 'PF-NATI-2025-1016',
        name: 'SANNI Ibrahim',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/14.jpg',
    },
    {
        id: 15,
        matricule: 'PF-NATI-2025-1017',
        name: 'ISSAKA Ibrahim',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/15.jpg',
    },
    {
        id: 16,
        matricule: 'PF-NATI-2025-1018',
        name: 'ISSAKA Mouhamed',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/16.jpg',
    },
    {
        id: 17,
        matricule: 'PF-NATI-2025-1019',
        name: 'YACOUBOU A. Ganiou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/17.jpg',
    },
    {
        id: 18,
        matricule: 'PF-NATI-2025-1020',
        name: 'SITA Hizbathou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/18.jpg',
    },
    {
        id: 19,
        matricule: 'PF-NATI-2025-1021',
        name: 'AZONGAN D. Jean Baptiste',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/19.jpg',
    },
    {
        id: 20,
        matricule: 'PF-NATI-2025-1022',
        name: 'DARI Samiratou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/20.jpg',
    },
    {
        id: 21,
        matricule: 'PF-NATI-2025-1023',
        name: 'YOLOU Alberic',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/21.jpg',
    },
    {
        id: 22,
        matricule: 'PF-NATI-2025-1024',
        name: 'ISSAKA Aboubacari',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/22.jpg',
    },
    {
        id: 23,
        matricule: 'PF-NATI-2025-1025',
        name: 'KOUTOULE Darius',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/23.jpg',
    },
    {
        id: 24,
        matricule: 'PF-NATI-2025-1026',
        name: 'GARADIMON Djamal',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/24.jpg',
    },
    {
        id: 25,
        matricule: 'PF-NATI-2025-1027',
        name: 'MAKIERI B. Faaris',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/25.jpg',
    },
    {
        id: 26,
        matricule: 'PF-NATI-2025-1028',
        name: 'ZIBO A. Moubarak',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/26.jpg',
    },
    {
        id: 27,
        matricule: 'PF-NATI-2025-1029',
        name: 'DRAMANE Samadou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/27.jpg',
    },
    {
        id: 28,
        matricule: 'PF-NATI-2025-1030',
        name: 'NKOUE Constant',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/28.jpg',
    },
    {
        id: 29,
        matricule: 'PF-NATI-2025-1031',
        name: 'BIO G. Madeleine',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/29.jpg',
    },
    {
        id: 30,
        matricule: 'PF-NATI-2025-1032',
        name: 'KOUYOGOU Miguela',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/30.jpg',
    },
    {
        id: 31,
        matricule: 'PF-NATI-2025-1033',
        name: 'TEKE Djalilou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/31.jpg',
    },
    {
        id: 32,
        matricule: 'PF-NATI-2025-1034',
        name: 'SABI M. Julien',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/32.jpg',
    },
    {
        id: 33,
        matricule: 'PF-NATI-2025-1035',
        name: 'SAHI Josephat',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/33.jpg',
    },
    {
        id: 34,
        matricule: 'PF-NATI-2025-1036',
        name: 'GBEHDE Baruch',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/34.jpg',
    },
    {
        id: 35,
        matricule: 'PF-NATI-2025-1037',
        name: 'ISSA A. Razack',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/35.jpg',
    },
    {
        id: 36,
        matricule: 'PF-NATI-2025-1038',
        name: 'BARKA Sylvanus',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/36.jpg',
    },
    {
        id: 37,
        matricule: 'PF-NATI-2025-1039',
        name: 'TABE S. Zaharane',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/37.jpg',
    },
    {
        id: 38,
        matricule: 'PF-NATI-2025-1040',
        name: 'ADJAGBA Stanley',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/38.jpg',
    },
    {
        id: 39,
        matricule: 'PF-NATI-2025-1041',
        name: 'KIANSI Christiane',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/39.jpg',
    },
    {
        id: 40,
        matricule: 'PF-NATI-2025-1042',
        name: 'GBEHDE Beata',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/40.jpg',
    },
    {
        id: 41,
        matricule: 'PF-NATI-2025-1043',
        name: 'OLYMPIO Joris',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/41.jpg',
    },
    {
        id: 42,
        matricule: 'PF-NATI-2025-1044',
        name: 'FARADITO Djalali',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/42.jpg',
    },
    {
        id: 43,
        matricule: 'PF-NATI-2025-1045',
        name: 'KASSA Ange',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/43.jpg',
    },
    {
        id: 44,
        matricule: 'PF-NATI-2025-1046',
        name: 'POURMATE Prudence',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/44.jpg',
    },
    {
        id: 45,
        matricule: 'PF-NATI-2025-1047',
        name: 'ABAYA Auguste',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/45.jpg',
    },
    {
        id: 46,
        matricule: 'PF-NATI-2025-1048',
        name: 'NEGUI M. José',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/46.jpg',
    },
    {
        id: 47,
        matricule: 'PF-NATI-2025-1050',
        name: 'GBEHDE Quartus',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/47.jpg',
    },
    {
        id: 48,
        matricule: 'PF-NATI-2025-1051',
        name: 'SAMBIENI D. Donné',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/48.jpg',
    },
    {
        id: 49,
        matricule: 'PF-NATI-2025-1052',
        name: 'BOUKARI Zouwebatou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/49.jpg',
    },
    {
        id: 50,
        matricule: 'PF-NATI-2025-1053',
        name: 'PRICO Firmine',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/50.jpg',
    },
    {
        id: 51,
        matricule: 'PF-NATI-2025-1054',
        name: 'TCHANTA Ingrid',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/51.jpg',
    },
    {
        id: 52,
        matricule: 'PF-NATI-2025-1055',
        name: 'KPARIKARE D. François',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/52.jpg',
    },
    {
        id: 53,
        matricule: 'PF-NATI-2025-1056',
        name: 'NENEHIDINI Y. Patrick',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/53.jpg',
    },
    {
        id: 54,
        matricule: 'PF-NATI-2025-1057',
        name: 'ODOUN Edison',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/54.jpg',
    },
    {
        id: 55,
        matricule: 'PF-NATI-2025-1058',
        name: 'BILERI Madjid',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/55.jpg',
    },
    {
        id: 56,
        matricule: 'PF-NATI-2025-1059',
        name: 'KOUTOULE S. Roland',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/56.jpg',
    },
    {
        id: 57,
        matricule: 'PF-NATI-2025-1060',
        name: 'ABIBOU Affoussath',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/57.jpg',
    },
    {
        id: 58,
        matricule: 'PF-NATI-2025-1061',
        name: 'KOUAGOU D. Perpétue',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/58.jpg',
    },
    {
        id: 59,
        matricule: 'PF-NATI-2025-1062',
        name: 'INOUA A. Sadath',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/59.jpg',
    },
    {
        id: 60,
        matricule: 'PF-NATI-2025-1063',
        name: 'KOUAGOU N. Antonio',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/60.jpg',
    },
    {
        id: 61,
        matricule: 'PF-NATI-2025-1064',
        name: 'ISSAKA B. Awali',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/61.jpg',
    },
    {
        id: 62,
        matricule: 'PF-NATI-2025-1065',
        name: 'SOULEYMANE Sabirou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/62.jpg',
    },
    {
        id: 63,
        matricule: 'PF-NATI-2025-1066',
        name: 'MPO Oscar',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/63.jpg',
    },
    {
        id: 64,
        matricule: 'PF-NATI-2025-1067',
        name: 'MAMOUDOU Mamoudou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/64.jpg',
    },
    {
        id: 65,
        matricule: 'PF-NATI-2025-1068',
        name: 'FOUSSENI A. Nadjibah',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/65.jpg',
    },
    {
        id: 66,
        matricule: 'PF-NATI-2025-1069',
        name: 'FOUSSENI A. Moudjibah',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/66.jpg',
    },
    {
        id: 67,
        matricule: 'PF-NATI-2025-1070',
        name: 'ADJAGBA Freda',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/67.jpg',
    },
    {
        id: 68,
        matricule: 'PF-NATI-2025-1072',
        name: 'MOUSSA Kamilou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/68.jpg',
    },
    {
        id: 69,
        matricule: 'PF-NATI-2025-1073',
        name: 'BOUKARI Ousseini',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/69.jpg',
    },
    {
        id: 70,
        matricule: 'PF-NATI-2025-1074',
        name: 'MONI Eveline',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/70.jpg',
    },
    {
        id: 71,
        matricule: 'PF-NATI-2025-1075',
        name: 'NOUANTI S. Florentin',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/71.jpg',
    },
    {
        id: 72,
        matricule: 'PF-NATI-2025-1006',
        name: 'CODJIA R. D. Megninse',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/72.jpg',
    },
    {
        id: 73,
        matricule: 'PF-NATI-2025-1001',
        name: 'DJIBRIL M. Maaloumou',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/73.jpg',
    },
    {
        id: 74,
        matricule: 'PF-NATI-2025-1071',
        name: 'YAKPARI T. Maurice',
        filieres: [
            "Initiation à l'informatique",
            'Intelligence artificielle',
            'Pilotage de drone',
        ],
        photo: 'images/74.jpg',
    },
]

// Admin credentials
const adminCredentials = {
    username: 'Programme FUTUR',
    password: '91RERDFUTUR',
}
